---
- name: Set setting w/ `systemsetup`
  block:
    - name: "Check '{{ systemsetup_setting.setting }}' already set"
      ansible.builtin.shell: "systemsetup -get{{ systemsetup_setting.setting }} | grep -wo {{ 'Never' if 'sleep' in systemsetup_setting.setting and systemsetup_setting.value | int == 0 else systemsetup_setting.value }}"
      register: result_systemsetup_get
      failed_when: false
      changed_when: false
    - name: "Set '{{ systemsetup_setting.setting }}' setting"
      ansible.builtin.command: "systemsetup {{ '-f' if systemsetup_setting.setting == 'remotelogin' else '' }} -set{{ systemsetup_setting.setting }} {{ systemsetup_setting.value }}"
      when: result_systemsetup_get.rc != 0
  become: true
  when: ansible_facts.os_family == 'Darwin'
