---
install_latex: False

#latex_packages:
#  - logreq
#  - biblatex

overridable_apps:
  - raycast
  # Office
  - pdf-expert
  # Privacy
  - little-snitch
  # Internet/Services
  - eddie
  # Social
  - signal
  - discord
